name: TypeCheck and report to OpenHands
on:
  pull_request:
jobs:
  typecheck:
    name: Typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install (and cache) PNPM dependencies
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install

      - name: Typecheck and report errors to OpenHands
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const exec = require('@actions/exec');

            let output = '';
            let error = '';

            const options = {};
            options.listeners = {
              stdout: (data: Buffer) => {
                output += data.toString();
              },
              stderr: (data: Buffer) => {
                error += data.toString();
              }
            };

            await exec.exec('pnpm', ['run', 'typescript'], options);

            console.log("TypeScript outputs: ", output);
            console.log("TypeScript errors: ", error);
